### ISSUE TITLE
% prefix to execute a single shell command broken

### ISSUE THREAD

**Issue by j-kleemann** [op3/hdtv#2]
The % prefix to execute a single shell command (also still found in the documentation) does not work anymore.
E.g. `%sleep 4` should execute `sleep 4` on the system shell waiting for the commands termination.
This prefix can be especially useful in HDTV batch files being executed using the `@` prefix, but also in the interactive commandline itself (altough there one can use the currently undocumented `Alt+!` keyboard shortcut for shell command execution).
In the meanwhile one can workaround the issue for batch files by using the `:` prefix to execute a python command by 
```
:hdtv>import subprocess
:hdtv>subprocess.run(["command","arg"])
```

When fixing the issue, one could think about improving the `shell` command to take arguments like `shell sleep 5` or `shell bash` with just `shell` defaulting to `shell sh` for an interactive shell, kind of adding an alias to `%` .
The `shell` command should then also give a help message via `shell -h` and later on could add even more options (e.g. an option to not wait for command termination or so).
The advantage would be a more consistent and readable interface superseding the cryptic `%` command (which is also not included in tab-autocompletion).
The same naturally holds for the `:` command to execute a python statement, altough this currently still works unlike the `%` command.

**Comment by op3** [comment]
Fixed in e86aed2078f537321d0a97511d77e8c310fd7b3e and a22ea0400555c43886167592401554a05be6af18.

For compatibility reasons that might come up in the [future](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-system), the prefix is now called `!`. `Alt+!` was removed.
