### ISSUE TITLE
@ prefix not recognized in a one-liner command (as with hdtv -e "cmd1 ; @file")

### ISSUE THREAD

**Issue by j-kleemann** [op3/hdtv#3]
The `@` prefix to execute a HDTV command file can not be used as a non-first statement in a one-liner multicommand e.g. `s g spectrum.tv ; @file` yields `ERROR: Command not recognized` and `s g spectrum.tv @file` yields `WARNING: @file.hdtv: no such file` with the later example being bad syntax anyway.
This is unfortunate when using the `-e` HDTV command line toggle to execute commands at startup when the `@` command is used as a second instruction, e.g. `hdtv -e "s g spectrum.tv ; @file"` again yields `ERROR: Command not recognized` and also
```
hdtv -e "s g spectrum.tv 
         @file"
``` 
yields `WARNING: @file.hdtv: no such file` as well.
As stated in issue #2 it might be nice to introduce a proper command in addition of `@` (keeping it only for backwards-compatibility) to benefit from tab-completition on the HDTV prompt and allowing to introduce an help message (and possibly other command options later on).

**Comment by op3** [comment]
I added an `exec` command for this purpose in f26876774ca248cba9bc90a08f6cbdec2c45e2fb.

> to benefit from tab-completition

tab-completion is already available when using `@`.

**Comment by j-kleemann** [comment]
> tab-completion is already available when using `@`.

Yes, but this is not what I was referring to: In the tab-completion at the `hdtv>` level `@`, `%`, and `:` do not appear, unlike the now new `exec` command for example.
This new command appearing in the root tab-completion level now is more visible for users, making them quickly aware of its availability, without having to read the doc and remembering the somewhat cryptic symbol.

Anyway, thank you and keep up the good work!
