### ISSUE TITLE
Tab autocomplete on "fit parameter status " and "fit parameter reset " yield unhandeled exception

### ISSUE THREAD

**Issue by j-kleemann** [op3/hdtv#4]
When trying to autocomple `fit parameter status ` on the hdtv prompt an exception is encountered.
Same for `fit parameter reset`.
No problems for `fit parameter status background ` which likewise has no options.

**Comment by op3** [comment]
Fixed in 21b018c32e60feaea803bec0f76ed8dc24f3e7ca. Thank you!
