### ISSUE TITLE
Bash prompt breaks/malformed when exiting HDTV by closing the spectra window

### ISSUE THREAD

**Issue by j-kleemann** [op3/hdtv#6]
My bash prompt acts strange after exiting hdtv by closing the spectra window (clicking the X button).
E.g. typed input on the bash does not appear in the terminal, although recognized by bash (can execute the invisible command), and entering an empty line (just return) does not create a new line, but shows a new prompt anyway: 
```
jk@JK-PC:~$ jk@JK-PC:~$ I echoed this by echo
jk@JK-PC:~$ but the command did not show up when I typed it!
jk@JK-PC:~$ jk@JK-PC:~$
```
I have to execute `reset` for it to work properly again.

**Comment by op3** [comment]
Fixed in 0555531e4d4105cff2b44b57e3ea5e118f746fce.
